font pango:JetBrainsMono Nerd Font 10
default_border pixel 2
default_floating_border pixel 2
gaps inner 7
gaps outer 3
smart_borders on

# Tokyo Night: border background text indicator child_border
client.focused          #7aa2f7 #1a1b26 #c0caf5 #7dcfff #7aa2f7
client.focused_inactive #3b4261 #1a1b26 #a9b1d6 #3b4261 #3b4261
client.unfocused        #292e42 #1a1b26 #565f89 #292e42 #292e42
client.urgent           #f7768e #1a1b26 #f7768e #f7768e #f7768e

output * bg $wallpaper fill
seat * hide_cursor 5000
